// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Poi.Id.InfraModel.DataAccess;

#nullable disable

namespace Poi.Id.InfraModel.Migrations
{
    [DbContext(typeof(IdDbContext))]
    [Migration("20240623152025_AddCreatedBy")]
    partial class AddCreatedBy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("HoSoNhanSuSeq")
                .HasMin(1L)
                .HasMax(2147483647L);

            modelBuilder.Entity("AppTenant", b =>
                {
                    b.Property<Guid>("AppsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantsId")
                        .HasColumnType("uuid");

                    b.HasKey("AppsId", "TenantsId");

                    b.HasIndex("TenantsId");

                    b.ToTable("AppTenant");
                });

            modelBuilder.Entity("AppUser", b =>
                {
                    b.Property<Guid>("AppsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("AppsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("HrmChucNangHrmNhomChucNang", b =>
                {
                    b.Property<Guid>("HrmChucNangId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HrmNhomChucNangId")
                        .HasColumnType("uuid");

                    b.HasKey("HrmChucNangId", "HrmNhomChucNangId");

                    b.HasIndex("HrmNhomChucNangId");

                    b.ToTable("HrmChucNangHrmNhomChucNang");
                });

            modelBuilder.Entity("HrmNhomChucNangHrmVaiTro", b =>
                {
                    b.Property<Guid>("HrmNhomChucNangId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HrmVaiTroId")
                        .HasColumnType("uuid");

                    b.HasKey("HrmNhomChucNangId", "HrmVaiTroId");

                    b.HasIndex("HrmVaiTroId");

                    b.ToTable("HrmNhomChucNangHrmVaiTro");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("PermissionRole");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.App", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.ChiNhanhVanPhong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<Guid?>("CoQuanDonViId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CoQuanDonViId");

                    b.HasIndex("TenantId");

                    b.ToTable("ChiNhanhVanPhongs");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.CoQuanDonVi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("CoQuanDonVis");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmChamCongDiemDanh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HrmCongKhaiBaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HrmTrangThaiChamCongId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HrmCongKhaiBaoId");

                    b.HasIndex("HrmTrangThaiChamCongId");

                    b.HasIndex("UserId");

                    b.ToTable("HrmChamCongDiemDanh");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmChucNang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Method")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<string>("TenChucNang")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("HrmChucNang");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmCongKhaiBao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("MaCongKhaiBao")
                        .HasColumnType("text");

                    b.Property<string>("TenCongKhaiBao")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("HrmCongKhaiBao");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmCongThucLuong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChiTietCongThuc")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("TenCongThuc")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("HrmCongThucLuong");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmDiemDanhHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("SnapShotPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HrmDiemDanhHistory");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmGiaiTrinhChamCong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HrmChamCongDiemDanhId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HrmCongKhaiBaoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LyDo")
                        .HasColumnType("text");

                    b.Property<Guid?>("NguoiXacNhanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HrmChamCongDiemDanhId");

                    b.HasIndex("HrmCongKhaiBaoId");

                    b.HasIndex("NguoiXacNhanId");

                    b.ToTable("HrmGiaiTrinhChamCong");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmHoSoNhanSu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChiNhanhVanPhongId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DanToc")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("KhuVucChuyenMonId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaHoSo")
                        .HasColumnType("text");

                    b.Property<string>("NgaySinh")
                        .HasColumnType("text");

                    b.Property<string>("NoiOHienNay")
                        .HasColumnType("text");

                    b.Property<string>("NoiSinh")
                        .HasColumnType("text");

                    b.Property<Guid?>("PhanLoaiNhanSuId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PhongBanBoPhanId")
                        .HasColumnType("uuid");

                    b.Property<string>("QueQuan")
                        .HasColumnType("text");

                    b.Property<string>("TenKhac")
                        .HasColumnType("text");

                    b.Property<string>("ThongTinThem")
                        .HasColumnType("jsonb");

                    b.Property<string>("ThuongTru")
                        .HasColumnType("text");

                    b.Property<string>("TonGiao")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VaiTroId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ViTriCongViecId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChiNhanhVanPhongId");

                    b.HasIndex("KhuVucChuyenMonId");

                    b.HasIndex("PhanLoaiNhanSuId");

                    b.HasIndex("PhongBanBoPhanId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("VaiTroId");

                    b.HasIndex("ViTriCongViecId");

                    b.ToTable("HrmHoSoNhanSu");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmKhuVucChuyenMon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MaKhuVuc")
                        .HasColumnType("text");

                    b.Property<string>("Ten")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("HrmKhuVucChuyenMon");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmNhomChucNang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("TenNhomChucNang")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("HrmNhomChucNang");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmPhanLoaiNhanSu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MaPhanLoai")
                        .HasColumnType("text");

                    b.Property<string>("Ten")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("HrmPhanLoaiNhanSu");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmThamSoLuong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DuongDanTichHop")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MaThamSoLuong")
                        .HasColumnType("text");

                    b.Property<string>("TenThamSoLuong")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("HrmThamSoLuong");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmTrangThaiChamCong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("MaTrangThai")
                        .HasColumnType("text");

                    b.Property<string>("MauSac")
                        .HasColumnType("text");

                    b.Property<string>("TenTrangThai")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("YeuCauGiaiTrinh")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("HrmTrangThaiChamCong");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmVaiTro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("TenVaiTro")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("HrmVaiTro");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmViTriCongViec", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("TenViTri")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("HrmViTriCongViec");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Method")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.PhongBanBoPhan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<Guid?>("ChiNhanhVanPhongId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChiNhanhVanPhongId");

                    b.HasIndex("ParentId");

                    b.HasIndex("TenantId");

                    b.ToTable("PhongBanBoPhans");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Prj.PrjCongViec", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CongViecChaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NhomCongViecId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenCongViec")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CongViecChaId");

                    b.HasIndex("NhomCongViecId");

                    b.HasIndex("TenantId");

                    b.ToTable("PrjCongViec");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Prj.PrjDuAnNvChuyenMon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsNhiemVuChuyenMon")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LinhVucId")
                        .HasColumnType("uuid");

                    b.Property<string>("MoTaDuAn")
                        .HasColumnType("text");

                    b.Property<Guid?>("PhongBanBoPhanId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuanLyDuAnId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenDuAn")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ToNhomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LinhVucId");

                    b.HasIndex("PhongBanBoPhanId");

                    b.HasIndex("QuanLyDuAnId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ToNhomId");

                    b.ToTable("PrjDuAnNvChuyenMon");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Prj.PrjLinhVuc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("TenLinhVuc")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("PrjLinhVuc");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Prj.PrjNhomCongViec", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DuAnNvChuyenMonId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("TenNhomCongViec")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DuAnNvChuyenMonId");

                    b.HasIndex("TenantId");

                    b.ToTable("PrjNhomCongViec");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Prj.PrjToNhom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("TenToNhom")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("PrjToNhom");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ManagerOfPhongBanBoPhanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PhongBanBoPhanId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("SurName")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("ManagerOfPhongBanBoPhanId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PhongBanBoPhanId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PrjDuAnNvChuyenMonUser", b =>
                {
                    b.Property<Guid>("PrjDuAnNvChuyenMonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ThanhVienDuAnId")
                        .HasColumnType("uuid");

                    b.HasKey("PrjDuAnNvChuyenMonId", "ThanhVienDuAnId");

                    b.HasIndex("ThanhVienDuAnId");

                    b.ToTable("PrjDuAnChuyenMonThanhVienDuAn", (string)null);
                });

            modelBuilder.Entity("PrjToNhomUser", b =>
                {
                    b.Property<Guid>("ThanhVienId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ThanhVienToNhomId")
                        .HasColumnType("uuid");

                    b.HasKey("ThanhVienId", "ThanhVienToNhomId");

                    b.HasIndex("ThanhVienToNhomId");

                    b.ToTable("PrjToNhomThanhVien", (string)null);
                });

            modelBuilder.Entity("PrjToNhomUser1", b =>
                {
                    b.Property<Guid>("LanhDaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanhDaoToNhomId")
                        .HasColumnType("uuid");

                    b.HasKey("LanhDaoId", "LanhDaoToNhomId");

                    b.HasIndex("LanhDaoToNhomId");

                    b.ToTable("PrjToNhomLanhDao", (string)null);
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.Property<Guid>("DirectReportsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManagersId")
                        .HasColumnType("uuid");

                    b.HasKey("DirectReportsId", "ManagersId");

                    b.HasIndex("ManagersId");

                    b.ToTable("UserUser");
                });

            modelBuilder.Entity("AppTenant", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.App", null)
                        .WithMany()
                        .HasForeignKey("AppsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poi.Id.InfraModel.DataAccess.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppUser", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.App", null)
                        .WithMany()
                        .HasForeignKey("AppsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poi.Id.InfraModel.DataAccess.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HrmChucNangHrmNhomChucNang", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Hrm.HrmChucNang", null)
                        .WithMany()
                        .HasForeignKey("HrmChucNangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poi.Id.InfraModel.DataAccess.Hrm.HrmNhomChucNang", null)
                        .WithMany()
                        .HasForeignKey("HrmNhomChucNangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HrmNhomChucNangHrmVaiTro", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Hrm.HrmNhomChucNang", null)
                        .WithMany()
                        .HasForeignKey("HrmNhomChucNangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poi.Id.InfraModel.DataAccess.Hrm.HrmVaiTro", null)
                        .WithMany()
                        .HasForeignKey("HrmVaiTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poi.Id.InfraModel.DataAccess.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poi.Id.InfraModel.DataAccess.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.ChiNhanhVanPhong", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.CoQuanDonVi", "CoQuanDonVi")
                        .WithMany()
                        .HasForeignKey("CoQuanDonViId");

                    b.HasOne("Poi.Id.InfraModel.DataAccess.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("CoQuanDonVi");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.CoQuanDonVi", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Group", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Tenant", "Tenant")
                        .WithMany("Groups")
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmChamCongDiemDanh", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Hrm.HrmCongKhaiBao", "HrmCongKhaiBao")
                        .WithMany()
                        .HasForeignKey("HrmCongKhaiBaoId");

                    b.HasOne("Poi.Id.InfraModel.DataAccess.Hrm.HrmTrangThaiChamCong", "HrmTrangThaiChamCong")
                        .WithMany()
                        .HasForeignKey("HrmTrangThaiChamCongId");

                    b.HasOne("Poi.Id.InfraModel.DataAccess.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("HrmCongKhaiBao");

                    b.Navigation("HrmTrangThaiChamCong");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmCongKhaiBao", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmCongThucLuong", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmDiemDanhHistory", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmGiaiTrinhChamCong", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Hrm.HrmChamCongDiemDanh", "HrmChamCongDiemDanh")
                        .WithMany()
                        .HasForeignKey("HrmChamCongDiemDanhId");

                    b.HasOne("Poi.Id.InfraModel.DataAccess.Hrm.HrmCongKhaiBao", "HrmCongKhaiBao")
                        .WithMany()
                        .HasForeignKey("HrmCongKhaiBaoId");

                    b.HasOne("Poi.Id.InfraModel.DataAccess.User", "NguoiXacNhan")
                        .WithMany()
                        .HasForeignKey("NguoiXacNhanId");

                    b.Navigation("HrmChamCongDiemDanh");

                    b.Navigation("HrmCongKhaiBao");

                    b.Navigation("NguoiXacNhan");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmHoSoNhanSu", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.ChiNhanhVanPhong", "ChiNhanhVanPhong")
                        .WithMany()
                        .HasForeignKey("ChiNhanhVanPhongId");

                    b.HasOne("Poi.Id.InfraModel.DataAccess.Hrm.HrmKhuVucChuyenMon", "KhuVucChuyenMon")
                        .WithMany()
                        .HasForeignKey("KhuVucChuyenMonId");

                    b.HasOne("Poi.Id.InfraModel.DataAccess.Hrm.HrmPhanLoaiNhanSu", "PhanLoaiNhanSu")
                        .WithMany()
                        .HasForeignKey("PhanLoaiNhanSuId");

                    b.HasOne("Poi.Id.InfraModel.DataAccess.PhongBanBoPhan", "PhongBanBoPhan")
                        .WithMany()
                        .HasForeignKey("PhongBanBoPhanId");

                    b.HasOne("Poi.Id.InfraModel.DataAccess.User", "User")
                        .WithOne("HrmHoSoNhanSu")
                        .HasForeignKey("Poi.Id.InfraModel.DataAccess.Hrm.HrmHoSoNhanSu", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poi.Id.InfraModel.DataAccess.Hrm.HrmVaiTro", "VaiTro")
                        .WithMany()
                        .HasForeignKey("VaiTroId");

                    b.HasOne("Poi.Id.InfraModel.DataAccess.Hrm.HrmViTriCongViec", "ViTriCongViec")
                        .WithMany()
                        .HasForeignKey("ViTriCongViecId");

                    b.Navigation("ChiNhanhVanPhong");

                    b.Navigation("KhuVucChuyenMon");

                    b.Navigation("PhanLoaiNhanSu");

                    b.Navigation("PhongBanBoPhan");

                    b.Navigation("User");

                    b.Navigation("VaiTro");

                    b.Navigation("ViTriCongViec");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmKhuVucChuyenMon", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmNhomChucNang", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmPhanLoaiNhanSu", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmTrangThaiChamCong", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmVaiTro", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Hrm.HrmViTriCongViec", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.PhongBanBoPhan", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.ChiNhanhVanPhong", "ChiNhanhVanPhong")
                        .WithMany()
                        .HasForeignKey("ChiNhanhVanPhongId");

                    b.HasOne("Poi.Id.InfraModel.DataAccess.PhongBanBoPhan", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.HasOne("Poi.Id.InfraModel.DataAccess.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("ChiNhanhVanPhong");

                    b.Navigation("Parent");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Prj.PrjCongViec", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Prj.PrjCongViec", "CongViecCha")
                        .WithMany()
                        .HasForeignKey("CongViecChaId");

                    b.HasOne("Poi.Id.InfraModel.DataAccess.Prj.PrjNhomCongViec", "NhomCongViec")
                        .WithMany("CongViec")
                        .HasForeignKey("NhomCongViecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poi.Id.InfraModel.DataAccess.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CongViecCha");

                    b.Navigation("NhomCongViec");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Prj.PrjDuAnNvChuyenMon", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Prj.PrjLinhVuc", "LinhVuc")
                        .WithMany()
                        .HasForeignKey("LinhVucId");

                    b.HasOne("Poi.Id.InfraModel.DataAccess.PhongBanBoPhan", "PhongBanBoPhan")
                        .WithMany()
                        .HasForeignKey("PhongBanBoPhanId");

                    b.HasOne("Poi.Id.InfraModel.DataAccess.User", "QuanLyDuAn")
                        .WithMany()
                        .HasForeignKey("QuanLyDuAnId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Poi.Id.InfraModel.DataAccess.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poi.Id.InfraModel.DataAccess.Prj.PrjToNhom", "ToNhom")
                        .WithMany("DuAn")
                        .HasForeignKey("ToNhomId");

                    b.Navigation("LinhVuc");

                    b.Navigation("PhongBanBoPhan");

                    b.Navigation("QuanLyDuAn");

                    b.Navigation("Tenant");

                    b.Navigation("ToNhom");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Prj.PrjLinhVuc", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Prj.PrjNhomCongViec", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Prj.PrjDuAnNvChuyenMon", "DuAnNvChuyenMon")
                        .WithMany("NhomCongViec")
                        .HasForeignKey("DuAnNvChuyenMonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poi.Id.InfraModel.DataAccess.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuAnNvChuyenMon");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Prj.PrjToNhom", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.User", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Group", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupId");

                    b.HasOne("Poi.Id.InfraModel.DataAccess.PhongBanBoPhan", "ManagerOfPhongBanBoPhan")
                        .WithMany("QuanLy")
                        .HasForeignKey("ManagerOfPhongBanBoPhanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Poi.Id.InfraModel.DataAccess.PhongBanBoPhan", "PhongBanBoPhan")
                        .WithMany("ThanhVien")
                        .HasForeignKey("PhongBanBoPhanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Poi.Id.InfraModel.DataAccess.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.HasOne("Poi.Id.InfraModel.DataAccess.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Group");

                    b.Navigation("ManagerOfPhongBanBoPhan");

                    b.Navigation("PhongBanBoPhan");

                    b.Navigation("Role");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PrjDuAnNvChuyenMonUser", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.Prj.PrjDuAnNvChuyenMon", null)
                        .WithMany()
                        .HasForeignKey("PrjDuAnNvChuyenMonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poi.Id.InfraModel.DataAccess.User", null)
                        .WithMany()
                        .HasForeignKey("ThanhVienDuAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrjToNhomUser", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.User", null)
                        .WithMany()
                        .HasForeignKey("ThanhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poi.Id.InfraModel.DataAccess.Prj.PrjToNhom", null)
                        .WithMany()
                        .HasForeignKey("ThanhVienToNhomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrjToNhomUser1", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.User", null)
                        .WithMany()
                        .HasForeignKey("LanhDaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poi.Id.InfraModel.DataAccess.Prj.PrjToNhom", null)
                        .WithMany()
                        .HasForeignKey("LanhDaoToNhomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.HasOne("Poi.Id.InfraModel.DataAccess.User", null)
                        .WithMany()
                        .HasForeignKey("DirectReportsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poi.Id.InfraModel.DataAccess.User", null)
                        .WithMany()
                        .HasForeignKey("ManagersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Group", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.PhongBanBoPhan", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("QuanLy");

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Prj.PrjDuAnNvChuyenMon", b =>
                {
                    b.Navigation("NhomCongViec");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Prj.PrjNhomCongViec", b =>
                {
                    b.Navigation("CongViec");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Prj.PrjToNhom", b =>
                {
                    b.Navigation("DuAn");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.Tenant", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Poi.Id.InfraModel.DataAccess.User", b =>
                {
                    b.Navigation("HrmHoSoNhanSu");
                });
#pragma warning restore 612, 618
        }
    }
}
